OrdererOrgs:
  - Name: Orderer
    Domain: client1.com
    Specs:
    - Hostname: orderer
PeerOrgs:
  - Name: Client1
    Domain: client1.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org1
    Domain: org1.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.com
    Template:
      Count: 1
    Users:
      Count: 1
