version: '2'

networks:
    fabric:

services:
    ca.org2.com:
        image: hyperledger/fabric-ca
        container_name: ca.org2.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca.org2.com
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6e844b659a7b29047993b92f9386ffbf6823f1571a0c1c94202362184a61f06e_sk
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw'
        volumes:
            - ../crypto-config/peerOrganizations/org2.com/ca/:/etc/hyperledger/fabric-ca-server-config
        networks:
            - fabric
    couchdb0:
        container_name: couchdb0
        image: hyperledger/fabric-couchdb
        ports:
            - "5984:5984"
        networks:
            - fabric
    peer0.org2.com:
        extends:
            file: docker-compose-base.yml
            service: peer
        container_name: peer0.org2.com
        environment:
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org2.com:7052
            - CORE_PEER_ID=peer0.org2.com
            - CORE_PEER_ADDRESS=peer0.org2.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.client1.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.com:7051
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_LOCALMSPID=Org2MSP
            - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@org2.com/tls/ca.crt
            - CORE_PEER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@org2.com/tls/client.crt
            - CORE_PEER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@org2.com/tls/client.key
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984

        volumes:
            - ../crypto-config/peerOrganizations/org2.com/peers/peer0.org2.com/msp:/var/hyperledger/msp
            - ../crypto-config/peerOrganizations/org2.com/peers/peer0.org2.com/tls:/var/hyperledger/tls
            - ../crypto-config/peerOrganizations/org2.com/users:/var/hyperledger/users
            - ../channel-artifacts/:/var/hyperledger/configs
        extra_hosts:
            - "orderer.client1.com:35.239.73.130"
            - "peer0.client1.com:104.155.172.13"
            - "peer0.org1.com:35.223.88.16"
        networks:
          fabric:
             aliases:
               - net
        ports:
          - 7051:7051
          - 7053:7053

    cli:
        container_name: cli
        image: hyperledger/fabric-tools
        tty: true
        environment:
          - GOPATH=/opt/gopath
          - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
          - CORE_LOGGING_LEVEL=DEBUG
          - CORE_PEER_ID=cli
          - CORE_PEER_ADDRESS=peer0.org2.com:7051
          - CORE_PEER_LOCALMSPID=Org2MSP
          - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.com/users/Admin@org2.com/msp
          - CORE_CHAINCODE_KEEPALIVE=10
        extra_hosts:
          - "orderer.client1.com:35.239.73.130"
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ../../chaincode/:/opt/gopath/src/github.com/
            # - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
            - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
        depends_on:
          - peer0.org2.com
        networks:
            - fabric
